name = "AxisKeysExtra"
uuid = "b7a0d2b7-1990-46dc-b5dd-87820ecd1b09"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.11"

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[weakdeps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
RectiGrids = "8ac6971d-971d-971d-971d-971d5ab1a71a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
DimensionalDataExt = "DimensionalData"
MakieExt = "Makie"
RectiGridsExt = "RectiGrids"
UnitfulExt = "Unitful"

[compat]
AxisKeys = "0.2.12"
DimensionalData = "0.23, 0.24, 0.25, 0.26, 0.27"
Makie = "0.21.2"
RectiGrids = "0.1.14"
Reexport = "1.2.2"
StructArrays = "0.6.12"
Unitful = "1"
julia = "1.9"
